image:
  tag: "main"

springProfiles:
  - int

ingress:
  host: catenax-vas-int.demo.catena-x.net

environment: "int"

applicationSecret:
  keycloak: <path:vas/int/keycloak#credentials-secret>
  cdq: <path:vas/int/cdq#api-key>

