name: "Sonar Cloud Workflow"

on:
  push:
    branches:
      - 'main'
      - 'dev'

    workflow_call:
      secrets:
        SONAR_TOKEN:
          required: true

jobs:
  Analysis:
    name: Analyse
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run yarn install
        uses: Borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run npm test:ci
        run: CHROMIUM_BIN=$(which chrome) npm run test:ci
      - uses: SonarSource/sonarcloud-github-action@master

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}